### ISSUE TITLE
[pyamgcl] Random solving failure when creating solver in a python for loop

### ISSUE THREAD

**Issue by Eydcao** [ddemidov/amgcl#178] opened 2020-12-22 06:44 UTC
Hello, dear Developers,

I am using pybind+amgcl for a physical simulation project and need to reconstruct the sparse system each time step. However, as we will see in the screenshot below, random failures of solving will occur if we create a solver in a python for-loop.

![image](https://user-images.githubusercontent.com/48085697/102857832-1b472d80-4464-11eb-9a91-eab065481696.png)

[test_PYAMGCL.zip](https://github.com/ddemidov/amgcl/files/5728236/test_PYAMGCL.zip)

Have attached the zip of the test files as well. Lots of thanks!

Yadi

**Comment by Eydcao** [comment] 2020-12-22 06:49
Just to exclude some potential issues from the system, the scipy.sparse.linalg.cg can produce correct results and also my hand-written, none-preconditioned cg solver.

**Comment by ddemidov** [comment] 2020-12-22 07:47
Thanks for reporting this, please see if the issue is fixed by 75b3dca.

**Comment by Eydcao** [comment] 2020-12-22 09:02
Sure, greatly done. I will try this fix very soon.

**Comment by Eydcao** [comment] 2020-12-22 09:12
It's fixed on my side, great done!

Thx~

**Closed** 2020-12-22 09:12 UTC
